#!/bin/bash
#echo line1 1<&2
#echo $1 1>&2
#echo line2 1>&2
#echo $2 1>&2
#if [ $1==bbb ]
#then 
#echo wtf
#fi 
#if [ $2 == bbb ]
#then 
#echo wtf2
#fi
if [ -z $1 ]
then
	exit 1
fi
if [ $1 == $2 ] 
then
#	echo passed
	echo 1
fi
